test:
	python3 solver.py input/solution_1.txt -o output/solution_1/

	python3 solver.py input/solution_4.txt -o output/solution_4/

	python3 solver.py input/solution_10.txt -o output/solution_10/ -a 1

	python3 solver.py input/solution_15.txt -o output/solution_15/ -a 1

	python3 solver.py input/solution_20.txt -o output/solution_20/ -a 1

	python3 generator.py input/15_puzzle_solution_20.txt -n 4 -c 20
	python3 solver.py input/15_puzzle_solution_20.txt -o output/15_puzzle_solution20/ -a 1

	python3 generator.py input/15_puzzle_solution_20.txt -n 4 -c 20
	python3 solver.py input/15_puzzle_solution_20.txt -o output/15_puzzle_solution20/ -a 1

	python3 generator.py input/24_puzzle_solution_25.txt -n 5 -c 25
	python3 solver.py input/24_puzzle_solution_25.txt -o output/24_puzzle_solution25/ -a 1

	python3 generator.py input/143_puzzle_solution_50.txt -n 12 -c 50
	python3 solver.py input/143_puzzle_solution_50.txt -o output/143_puzzle_solution50/ -a 1

	python3 solver.py input/solution_31.txt -o output/solution_31/ -a 1

